spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGO_URI}

jwt:
  secret: ${JWT_KEY}

server:
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
  port: 8081
